
namespace app.Models
{
    public class Challenges
    {
        public double twelveAssistStreakCount { get; set; }
        public double abilityUses { get; set; }
        public double acesBefore15Minutes { get; set; }
        public double alliedJungleMonsterKills { get; set; }
        public double baronBuffGoldAdvantageOverThreshold { get; set; }
        public double baronTakedowns { get; set; }
        public double blastConeOppositeOpponentCount { get; set; }
        public double bountyGold { get; set; }
        public double buffsStolen { get; set; }
        public double completeSupportQuestInTime { get; set; }
        public double controlWardsPlaced { get; set; }
        public double damagePerMinute { get; set; }
        public double damageTakenOnTeamPercentage { get; set; }
        public double dancedWithRiftHerald { get; set; }
        public double deathsByEnemyChamps { get; set; }

        public double dodgeSkillShotsSmallWindow { get; set; }
        public double doubleAces { get; set; }
        public double dragonTakedowns { get; set; }
        public float earliestBaron { get; set; }
        public double earlyLaningPhaseGoldExpAdvantage { get; set; }
        public double effectiveHealAndShielding { get; set; }
        public double elderDragonKillsWithOpposingSoul { get; set; }
        public double elderDragonMultikills { get; set; }
        public double enemyChampionImmobilizations { get; set; }
        public double enemyJungleMonsterKills { get; set; }
        public double epicMonsterKillsNearEnemyJungler { get; set; }
        public double epicMonsterKillsWithin30SecondsOfSpawn { get; set; }
        public double epicMonsterSteals { get; set; }
        public double epicMonsterStolenWithoutSmite { get; set; }
        public double firstTurretKilled { get; set; }
        public double flawlessAces { get; set; }
        public double fullTeamTakedown { get; set; }
        public double gameLength { get; set; }
        public double getTakedownsInAllLanesEarlyJungleAsLaner { get; set; }
        public double goldPerMinute { get; set; }
        public double hadOpenNexus { get; set; }
        public double immobilizeAndKillWithAlly { get; set; }
        public double initialBuffCount { get; set; }
        public double initialCrabCount { get; set; }
        public double jungleCsBefore10Minutes { get; set; }
        public double junglerTakedownsNearDamagedEpicMonster { get; set; }
        public double kTurretsDestroyedBeforePlatesFall { get; set; }
        public double kda { get; set; }
        public double killAfterHiddenWithAlly { get; set; }
        public double killParticipation { get; set; }
        public double killedChampTookFullTeamDamageSurvived { get; set; }
        public double killingSprees { get; set; }
        public double killsNearEnemyTurret { get; set; }
        public double killsOnOtherLanesEarlyJungleAsLaner { get; set; }
        public double killsOnRecentlyHealedByAramPack { get; set; }
        public double killsUnderOwnTurret { get; set; }
        public double killsWithHelpFromEpicMonster { get; set; }
        public double knockEnemyIntoTeamAndKill { get; set; }
        public double landSkillShotsEarlyGame { get; set; }
        public double laneMinionsFirst10Minutes { get; set; }
        public double laningPhaseGoldExpAdvantage { get; set; }
        public double legendaryCount { get; set; }
        public double lostAnInhibitor { get; set; }
        public double maxCsAdvantageOnLaneOpponent { get; set; }
        public double maxKillDeficit { get; set; }
        public double maxLevelLeadLaneOpponent { get; set; }
        public double mejaisFullStackInTime { get; set; }
        public double moreEnemyJungleThanOpponent { get; set; }
        public double multiKillOneSpell { get; set; }
        public double multiTurretRiftHeraldCount { get; set; }
        public double multikills { get; set; }
        public double multikillsAfterAggressiveFlash { get; set; }
        public double outerTurretExecutesBefore10Minutes { get; set; }
        public double outnumberedKills { get; set; }
        public double outnumberedNexusKill { get; set; }
        public double perfectDragonSoulsTaken { get; set; }
        public double perfectGame { get; set; }
        public double pickKillWithAlly { get; set; }
        public double playedChampSelectPosition { get; set; }
        public double poroExplosions { get; set; }
        public double quickCleanse { get; set; }
        public double quickFirstTurret { get; set; }
        public double quickSoloKills { get; set; }
        public double riftHeraldTakedowns { get; set; }
        public double saveAllyFromDeath { get; set; }
        public double scuttleCrabKills { get; set; }
        public double shortestTimeToAceFromFirstTakedown { get; set; }
        public double skillshotsDodged { get; set; }
        public double skillshotsHit { get; set; }

        public double snowballsHit { get; set; }
        public double soloBaronKills { get; set; }
        public double soloKills { get; set; }
        public double soloTurretsLategame { get; set; }
        public double stealthWardsPlaced { get; set; }
        public double survivedSingleDigitHpCount { get; set; }
        public double survivedThreeImmobilizesInFight { get; set; }
        public double takedownOnFirstTurret { get; set; }
        public double takedowns { get; set; }
        public double takedownsAfterGainingLevelAdvantage { get; set; }
        public double takedownsBeforeJungleMinionSpawn { get; set; }
        public double takedownsFirst25Minutes { get; set; }
        public double takedownsFirstXMinutes { get; set; }
        public double takedownsInAlcove { get; set; }
        public double takedownsInEnemyFountain { get; set; }
        public double teamBaronKills { get; set; }
        public double teamDamagePercentage { get; set; }
        public double teamElderDragonKills { get; set; }
        public double teamRiftHeraldKills { get; set; }
        public double teleportTakedowns { get; set; }
        public double thirdInhibitorDestroyedTime { get; set; }
        public double threeWardsOneSweeperCount { get; set; }
        public double tookLargeDamageSurvived { get; set; }
        public double turretPlatesTaken { get; set; }

        public double turretsTakenWithRiftHerald { get; set; }
        public double turretTakedowns { get; set; }
        public double twentyMinionsIn3SecondsCount { get; set; }
        public double twoWardsOneSweeperCount { get; set; }
        public double unseenRecalls { get; set; }
        public double visionScoreAdvantageLaneOpponent { get; set; }
        public double visionScorePerMinute { get; set; }

        public double wardsGuarded { get; set; }
        public double wardTakedowns { get; set; }
        public double wardTakedownsBefore20M { get; set; }
    }
}